// <auto-generated />
using Jun.Core.Domain.Entity;
using Jun.Data.Context;
using Jun.Domain.Entity.Org;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Jun.Data.Migrations
{
    [DbContext(typeof(JunDbContext))]
    partial class JunDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Jun.Domain.Entity.Org.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<string>("Address");

                    b.Property<string>("Bank");

                    b.Property<string>("CnName");

                    b.Property<string>("Code");

                    b.Property<int>("CompType");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("ContactTelephone");

                    b.Property<DateTime>("CreateOn");

                    b.Property<string>("CreateStaffName");

                    b.Property<int>("CreateUserId");

                    b.Property<string>("Des");

                    b.Property<string>("EnName");

                    b.Property<string>("Fax");

                    b.Property<string>("Homepage");

                    b.Property<string>("LogoPath");

                    b.Property<string>("Phone");

                    b.Property<string>("PostCode");

                    b.Property<string>("ShortName");

                    b.Property<int>("Status");

                    b.Property<string>("Tax");

                    b.Property<DateTime>("UpdateOn");

                    b.Property<string>("UpdateStaffName");

                    b.Property<int>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("SGEAP_Org_Company");
                });

            modelBuilder.Entity("Jun.Domain.Entity.Sys.MenuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreateOn");

                    b.Property<string>("CreateStaffName");

                    b.Property<int>("CreateUserId");

                    b.Property<string>("IconResource");

                    b.Property<bool>("IsVisible");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentId");

                    b.Property<string>("Remark");

                    b.Property<int>("SequenceIndex");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdateOn");

                    b.Property<string>("UpdateStaffName");

                    b.Property<int>("UpdateUserId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SGEAP_Sys_Menu");
                });

            modelBuilder.Entity("Jun.Domain.Entity.Sys.MenuEntity", b =>
                {
                    b.HasOne("Jun.Domain.Entity.Sys.MenuEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
