// <auto-generated />
using Jun.Core.Domain.Entity;
using Jun.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Jun.Data.Migrations
{
    [DbContext(typeof(JunDbContext))]
    partial class JunDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Jun.Domain.Entity.Sys.MenuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreateOn");

                    b.Property<string>("CreateStaffName");

                    b.Property<int>("CreateUserId");

                    b.Property<string>("IconResource");

                    b.Property<bool>("IsVisible");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentID");

                    b.Property<string>("Remark");

                    b.Property<int>("SequenceIndex");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdateOn");

                    b.Property<string>("UpdateStaffName");

                    b.Property<int>("UpdateUserId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.ToTable("dbSet");
                });

            modelBuilder.Entity("Jun.Domain.Entity.Sys.MenuEntity", b =>
                {
                    b.HasOne("Jun.Domain.Entity.Sys.MenuEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");
                });
#pragma warning restore 612, 618
        }
    }
}
